### ISSUE TITLE
get pool result?

### ISSUE THREAD

**Issue by ccnankai** [Yuliang-Liu/Curve-Text-Detector#17]
Thank you for your perfect job.
I downloaded the model and put it in the specified folder , run the demo.py ,but the detection location is not as accurate as the image in  readme.Position offsets often occur or  Missing half of the word on the left and right sides.
can you give me some advice?

![442](https://user-images.githubusercontent.com/33537489/46648707-d5765580-cbc8-11e8-8937-cc01862b6e4b.jpg)
![33](https://user-images.githubusercontent.com/33537489/46648772-1e2e0e80-cbc9-11e8-990b-dd55aa81f4f6.jpg)

**Comment by Yuliang-Liu** [comment]
Hi there,
The results are correct, but I know they look not very well for now. 
Because for fair comparison and easy reproduction, the method only used provided training data without any tricks, which may restrict its generalization ability to some extent. Using syntext or MLT pre-trained model to finetune on this dataset or testing images with larger scale may be good ways to improve the result.

You can also refer to some recent papers for curve text detection. Our recent solution is a segmentation based method, which can remarkably improve the detection performance and it can be much better in solving "Missing parts" problems. I will send some examples to your email.

In a word, the project is a little bit outdated. A new version of curved-text-detector is scheduled to release in the future.

**Comment by ccnankai** [comment]
@Yuliang-Liu 
thank you very much
