### ISSUE TITLE
some difference between the release model and paper result.

### ISSUE THREAD

**Issue by 10183308** [Yuliang-Liu/Curve-Text-Detector#2]
Thank you for the release code.

And some difference between the release model results and the paper result.
 In the paper ,you reulst is so good.
But the release code model is not the same effects with the paper.
Even some result is not good compare with the CTPN.

Could you give some tips for us ?

thank you  very much.

**Comment by Yuliang-Liu** [comment]
Hi there,

The testing result should be the same with the paper. If you simply run the test.sh, it uses the nms mode which would be worse a little and you can set pnms to true in the yml file to achieve the same result.

If you mean visualization performance,  that's because the detecting visualization is just not from the model we uploaded. The tloc does smooth the detection and achieves the best results in ctw1500, but it may reduce its visualization performance in detecting some strongly curve text. And simply using ctd looks much better in such cases.  I believe many methods not just CTPN can achieve good results in "some" cases, but we do compare them with the whole dataset in terms of F-measure. 

Many thanks for your comment. It reminds me maybe simply using IoU > 0.5 is not enough to evaluate curve text detection.

We will continually to update this repository and I will upload some model files and our model later, which I hope it can be helpful.

**Comment by 10183308** [comment]
hi, 
thak you for your reply.

I am looking  forward to your new  model .


thank you very much
