### ISSUE TITLE
caffe compiling problem:box_annotator_ohem_layer.cu(50): error: a template argument may not reference a local type

### ISSUE THREAD

**Issue by wenston2006** [Yuliang-Liu/Curve-Text-Detector#23]
I met a problem during compiling caffe, I post the screenshot image as below. The problem is "box_annotator_ohem_layer.cu(50): error: a template argument may not reference a local type"; I add "-std=C++11" in makefile of caffe, however , the problem is still there. So have you met the problem during compiling caffe? 

I use Ubuntu16.04, cuda9.0, cudnn7.0.3;
![screenshot from 2018-12-13 14-27-54](https://user-images.githubusercontent.com/18213760/49920098-f4a0a480-fee3-11e8-81b9-fea25f0f63b4.png)

**Comment by Yuliang-Liu** [comment]
See if this helps:

"box_annotator_ohem_layer uses C++11 features, you need to make changes to the makefile"

modified makefile:

ifeq ($(DEBUG), 1)
    
    COMMON_FLAGS += -DDEBUG -g -O0 -std=c++11
    NVCCFLAGS += -G
else
    
    COMMON_FLAGS += -DNDEBUG -O2 -std=c++11
endif

From：https://blog.csdn.net/Bankeey/article/details/77573860 

Have you maked clean before you recomplied the caffe? It seems you have built on your own caffe, and I recommend you to use the caffe of this repository to avoid some unpredictable issues because we have modified many things of the caffe.

**Comment by wenston2006** [comment]
Thank you for your reply!I'll have a try.

**Comment by xieyufei1993** [comment]
i meet the same question,have you solved it?
@wenston2006
