### ISSUE TITLE
Directly running my_train.sh still can not successfully train a model which achieve 73.2% Hmean

### ISSUE THREAD

**Issue by uunnhh** [Yuliang-Liu/Curve-Text-Detector#5]
Thank you for publishing the code, but directly running my_train.sh still can not successfully train a model which achieve 73.2% Hmean, Could you provide more specific training details?

**Comment by Yuliang-Liu** [comment]
Hi there,
This code is sorted for easily reproducing the results, it may have slight differences. We have tested the code before we uploaded it and it should achieve almost 72.8% without using pnms. Because the lacking of the training data, the save models have some deviation. You can simply save more models to test (by lower the SNAPSHOT_ITERS in yml file).
As I remembered, I don't use any trick to improve the results. 

Thanks for your comment. Merry Christmas
