### ISSUE TITLE
[Features] Annotation Tools-Image Rotation, Distorted polygonal box!

### ISSUE THREAD

**Issue by innat** [Yuliang-Liu/Curve-Text-Detector#53]
Hi @Yuliang-Liu me again :) 

I've encountered two phenomena of this annotation tools. I understand this tool is not perfect, but really promising. 

However, When we load an image on this tool, is it possible to rotate any degree (0, 90, ..)? I mean, while annotating I observed, an image which is good shape normally, but when load with these tools, it rotated somehow and pretty pesky to annotate. I hope you understand what I mean. I read the manual but didn't mention any key features that could rotate the image.

Second, which is very important I think. You suggested not to resize the image while annotating to much. I observed, sometimes (let's say) you make a polygonal box with 3 different text region nicely. But if we zoom in or out the image, it breaks somehow Or, sometimes if you re-open the software, it also seems to occur. 

Any catch?

**Comment by Yuliang-Liu** [comment]
@innat No, it can't rotate. Why rotatation is needed?  When you press 'k', you have two way to align and click: (a) press 'space' for x axis alignment; (b) press 'shift+click' for y axis alignment. It should be enough to handle all kind.

Yeah, the breaking bug caused by zoom in or out doesn't affect the final result.  If you find it breaks after re-open or next and back to the same image, the annotation is wrong and should be deleted. This should happen only when you did not annotate in the right way.

Sorry, we should have updated our newest version but still no ETA.  There are so many amazing tools available online like [labelme](https://github.com/wkentaro/labelme) (you recommended :D).

**Comment by innat** [comment]
Hmm, thank you so much for the clarification. I will keep that in mind when using these tools. And I didn't recommend labelme tools as because I didn't use it, but I think it's interesting to try out. :)
